CREATE TABLE `bans` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`banned` VARCHAR(50) NOT NULL DEFAULT '0',
	`banner` VARCHAR(50) NOT NULL,
	`reason` VARCHAR(150) NOT NULL DEFAULT '0',
	`expires` DATETIME NOT NULL,
	`timestamp` DATETIME NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=121
;